back-end/LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("courses.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("", include("apps.authentication.urls")),  # Auth routes - login / register
    path("", include("apps.home.urls")),  # UI Kits Html files
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/LMS/courses/models.py
from django.utils import timezone
from django.db import models
from django.utils.text import slugify  # auto create slug
from django.db.models.signals import pre_save  # presave auto create and save
from django.template.defaultfilters import truncatechars
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
import random
from django_ckeditor_5.fields import CKEditor5Field
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.urls import reverse

# Categoriess
# Color


class Categories(models.Model):
    choice_icon = (
        ('fab fa-python', 'python'),
        ('fab fa-java', 'java'),
        ('fas fa-snowman', 'snowman')
    )

    icon = models.CharField(choices=choice_icon, max_length=200, null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by('-id')

####### AUTHOR models#############


class Department(models.Model):
    department_profile = models.ImageField(
        upload_to="author", default='author/2021-11-19-14-04-25_0.png')
    name = models.CharField(max_length=100, null=True)
    about_department = CKEditor5Field()
    slug = models.SlugField(default='', max_length=500,
                            null=True, blank=True,)
    created_at = models.DateTimeField(
        default=timezone.now, editable=False)

    @property
    def short_description(self):
        return truncatechars(self.about_author, 20)

    def img_preview(self):
        return mark_safe('<img src="{}" width="80" />'.format(self.department_profile.url))
    img_preview.short_description = 'Image'
    img_preview.allow_tags = True

    def __str__(self):
        return self.name

    def author_snippet(self):
        return self.about_author[:300] + "..."


class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=100)
    number = models.IntegerField(default=0)

    def __str__(self):
        return self.language


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_review = models.CharField(max_length=100)
    comment = models.CharField(max_length=1000)

    def __str__(self):
        return self.course_review + " - " + self.comment

# COURSE


class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return timezone.now()


class Course(models.Model):
    STATUS = (
        ('XEM ĐƯỢC', 'XEM ĐƯỢC'),
        ('NHÁP', 'NHÁP'),
    )
    title = models.CharField(max_length=500)
    created_at = models.DateTimeField(default=timezone.now)
    update_at = AutoDateTimeField(default=timezone.now, editable=False)
    author = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    level = models.ForeignKey(
        Level, on_delete=models.CASCADE, null=True, blank=True)
    description = CKEditor5Field()
    price = models.IntegerField(null=True, default=0, blank=True)
    discount = models.IntegerField(null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True,blank=True)
    date_start = models.DateField(null=True, blank=True)
    slug = models.SlugField(default='', max_length=500,
                            null=True, blank=True, editable=False)
    status = models.CharField(
        choices=STATUS, default='NHÁP', max_length=100, null=True)
    featured_image = models.ImageField(
        upload_to="featured_img", default='static/course_all.png', null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['id']

    def short_description(self):
        return truncatechars(self.description, 20)

    def img_preview(self):
        return mark_safe('<img src="{}" width="80" />'.format(self.featured_image.url))
    img_preview.short_description = 'Image'
    img_preview.allow_tags = True

    def get_absolute_url(self):
        return reverse("course_details", kwargs={'slug': self.slug})
    
    def get_edit_url(self):
        return reverse("edit_course", kwargs={'slug': self.slug})

    @staticmethod
    def autocomplete_search_fields():
        return 'author', 'category'
# Tự tạo slug cho Course


def create_slug_course(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug_course(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver_course(sender, instance, *args, **kwargs):
    if instance.pk:
        try:
            original_instance = Course.objects.get(pk=instance.pk)
            if original_instance.title != instance.title:  # Check if the name has changed
                instance.slug = create_slug_course(instance)
        except Course.DoesNotExist:
            instance.slug = create_slug_course(instance)
    else:
        if not instance.slug:
            instance.slug = create_slug_course(instance)

# Tạo slug cho author


def create_slug_author(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Department.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug_author(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver_author(sender, instance, *args, **kwargs):
    if instance.pk:  # Check if the instance already exists in the database
        try:
            original_instance = Department.objects.get(pk=instance.pk)
            if original_instance.name != instance.name:  # Check if the name has changed
                instance.slug = create_slug_author(instance)
        except Department.DoesNotExist:
            instance.slug = create_slug_author(instance)
    else:
        if not instance.slug:
            instance.slug = create_slug_author(instance)


# PreSave sau khi Save
pre_save.connect(pre_save_post_receiver_course, Course)
pre_save.connect(pre_save_post_receiver_author, Department)


class What_you_learn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return "Lesson: " + self.name + " -  " + "Course: " + self.course.title

    class Meta:
        ordering = ['id']


class Video(models.Model):
    thumbnail = models.ImageField(
        upload_to="Yt_Thumbnail", default="Yt_Thumbnail/youtube-thumbnails.jpg", null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    youtube_id = models.CharField(max_length=200)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title


def create_course(instance, select_course=None):
    course = instance.lesson.course
    if select_course is not None:
        course = select_course
    return course

# Tự động điền course vào field -gg


def autofill_course(sender, instance, *args, **kwargs):
    if not instance.course:
        instance.course = create_course(instance)


class Document(models.Model):
    TYPE = (
        ('pdf', 'pdf'),
        ('docx', 'docx'),
        ('pptx', 'pptx'),
        ('rar', 'rar'),
    )
    name = models.CharField(max_length=100)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    file = models.FileField(upload_to="Documents",
                            max_length=100, null=True)
    file_type = models.CharField(
        choices=TYPE, max_length=10, null=True, blank=True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.name


pre_save.connect(autofill_course, Video)
pre_save.connect(autofill_course, Document)


class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title


class Payment(models.Model):
    order_id = models.CharField(max_length=100, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    user_course = models.ForeignKey(
        UserCourse, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name + " -- " + self.course.title


difficulties = (
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Hard', 'Hard'),
)

# --------QUIZ------------


class Quizzes(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

back-end/LMS/apps/templates/courses-app/forms/form-category.html
{% extends 'includes/form.html' %}

{% block title %} Department Form {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}

{% block header_page %}
<!-- Table headers will go here -->
<h6 class="h2 text-white d-inline-block mb-0">Category</h6>
<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="/categorys">Departments</a></li>
        {% if form_type == 'detail-form' %}
        <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Course</li>
        {% endif %}
    </ol>
</nav>
{% endblock %}


{% block header_form %}
<!-- this is header form -->
{% if form_type != 'detail-form' %}
<h1 class="mb-1">Create Course</h1>
<button id="courseButton" class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" style="display: none;">Save</button>
{% endif %}
{% endblock %}

{% block body_form %}
<!-- this is form content -->
    {% if form_type == 'detail-form' %}
    <form id="courseForm" action="{%url 'edit_category' category.id%}" method="post">
    {% else %}
    <form id="courseForm" action="{%url 'create_category' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
    </form>
    {% endblock %}

    {% block action_form %}
    <!-- this is form content if it eddit -->
    {% if form_type == 'detail-form' %}
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="mb-1">{{ category.name }}</h3>
            <a id="courseButton" href="#" class="btn btn-sm btn-info w-100 my-2" style=" display: none;">Save</a>
            <a href="#" class="btn btn-sm btn-info w-100 my-2">Duplicate</a>
            <button id="deleteCourse" data-toggle="modal" data-target="#deleteModal"
                class="btn btn-sm btn-danger w-100 my-2">Delete</button>
            <a href="#" class="btn btn-sm btn-success w-100 my-2">Archive</a>
        </div>
    </div>
    {% endif %}

    {% if category %}
    {% include "courses-app/modal/deleteModal.html" with url_name="delete_category" id=category.id %}
    {% endif %}

    {% endblock %}
    <!-- Specific JS goes HERE -->
    {% block javascripts %}
    {% endblock javascripts %}

back-end/LMS/apps/templates/courses-app/forms/form-course.html
{% extends 'includes/form.html' %}

{% block title %} Course Form {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}

{% block header_page %}
<!-- Table headers will go here -->
<h6 class="h2 text-white d-inline-block mb-0">Courses</h6>
<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="/courses">Courses</a></li>
        {% if form_type == 'detail-form' %}
        <li class="breadcrumb-item active" aria-current="page">{{ course.title }}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Course</li>
        {% endif %}
    </ol>
</nav>
{% endblock %}


{% block header_form %}
<!-- this is header form -->
{% if form_type != 'detail-form' %}
<h1 class="mb-1">Create Course</h1>
<button id="courseButton" class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" style="display: none;">Save</button>
{% endif %}
{% endblock %}

{% block body_form %}
<!-- this is form content -->
{% if form_type == 'detail-form' %}
<form id="courseForm" action="{%url 'edit_course' course.id%}" method="post">
{% else %}
<form id="courseForm" action="{%url 'create_courses' %}" method="post">
{% endif %}
        {% csrf_token %}
        <div class="pl-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    {{ form.title | as_crispy_field }}
                </div>
            </div>
        </div>
        <div class="pl-lg-4">
            <div class="row">
                <div class="col-lg-4">
                    {{ form.author | as_crispy_field }}

                </div>
                <div class="col-lg-4">
                    {{ form.category | as_crispy_field }}
                </div>

                <div class="col-lg-4">
                    {{ form.language | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    {{ form.price | as_crispy_field }}
                </div>
                <div class="col-lg-6">
                    {{ form.discount | as_crispy_field }}
                </div>
            </div>
        </div>
        <hr class="my-4">
        <!-- Description -->
        <h6 class="heading-small text-muted mb-4">Description</h6>
        <div class="pl-lg-4">
            {{ form.description | as_crispy_field }}
        </div>

        <hr class="my-4">
        <!-- Address -->
        <h6 class="heading-small text-muted mb-4">Contact information</h6>
        <div class="pl-lg-4">
            <div class="row">
                <div class="col-md-4">
                    {{ form.status | as_crispy_field }}
                </div>
                <div class="col-lg-4">
                    {{ form.language | as_crispy_field }}
                </div>
                <div class="col-lg-4">
                    {{ form.date_start | as_crispy_field }}
                </div>
            </div>
        </div>

    </form>
    {% endblock %}

    {% block extends_field %}
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" colspan="2">Lessons</th>
                </tr>
            </thead>
            {% if lesson_set %}
                {% for lesson in lesson_set %}
                <tr id="lesson-{{ lesson.id }}" class="child_data_table" data-id="{{ lesson.id }}">
                    <td class="w-100 budget py-3" style="font-size: 15px;">
                        {{ lesson.name }}
                    </td>
                    <td
                        <a id="deleteLesson-{{ lesson.id }}" class="float-right" onclick="deleteLesson({{ lesson.id }})" url="{% url 'delete_lesson' lesson.id %}">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
            <tr id="add_lesson_row" class="child_data_table">
                <td class="budget text-muted" colspan="2">
                    <button class="btn add_lesson">+ Add lesson to course</button>
                </td>
            </tr>
            <tr id="input_add_lesson_row" class="child_data_table" style="display:none;">
                <td class="budget text-muted" >
                    <input type="text" class="form-control lesson_input">
                </td>
                <td class="align-items-center">
                    <button class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" onclick="addLesson({{ course.id }})">Add</button>
                    <button class="btn btn-sm btn-danger py-2 px-4 mx-3 mb-2" onclick="toggleInput()">Cancel</button>
                </td>
            </tr>
        </table>
    {% endblock %}

    {% block action_form %}
    <!-- this is form content -->
    {% if form_type == 'detail-form' %}
    <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="mb-1">{{ course.title }}</h3>
            <a id="courseButton" href="#" class="btn btn-sm btn-info w-100 my-2" style=" display: none;">Save</a>
            <a href="#" class="btn btn-sm btn-info w-100 my-2">Duplicate</a>
            <button id="deleteCourse" data-toggle="modal" data-target="#deleteModal"
                class="btn btn-sm btn-danger w-100 my-2">Delete</button>
            <a href="#" class="btn btn-sm btn-success w-100 my-2">Archive</a>
        </div>
    </div>
    {% endif %}
    {% endblock %}

    {% block modal %}
    
    {% if course %}
    {% include "courses-app/modal/deleteModal.html" with url_name="delete_course" id=course.id %}
    {% endif %}
    

    {% endblock %}

    <!-- Specific JS goes HERE -->
    {% block javascripts %}
    {% endblock javascripts %}

back-end/LMS/apps/templates/courses-app/forms/form-department.html
{% extends 'includes/form.html' %}

{% block title %} Department Form {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}

{% block header_page %}
<!-- Table headers will go here -->
<h6 class="h2 text-white d-inline-block mb-0">Courses</h6>
<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="/departments">Departments</a></li>
        {% if form_type == 'detail-form' %}
        <li class="breadcrumb-item active" aria-current="page">{{ department.name }}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Course</li>
        {% endif %}
    </ol>
</nav>
{% endblock %}


{% block header_form %}
<!-- this is header form -->
{% if form_type != 'detail-form' %}
<h1 class="mb-1">Create Course</h1>
<button id="courseButton" class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" style="display: none;">Save</button>
{% endif %}
{% endblock %}

{% block body_form %}
<!-- this is form content -->
    {% if form_type == 'detail-form' %}
    <form id="courseForm" action="{%url 'edit_department' department.id%}" method="post">
    {% else %}
    <form id="courseForm" action="{%url 'create_department' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
    </form>
    {% endblock %}

    {% block action_form %}
    <!-- this is form content if it eddit -->
    {% if form_type == 'detail-form' %}
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="mb-1">{{ department.name }}</h3>
            <a id="courseButton" href="#" class="btn btn-sm btn-info w-100 my-2" style=" display: none;">Save</a>
            <a href="#" class="btn btn-sm btn-info w-100 my-2">Duplicate</a>
            <button id="deleteCourse" data-toggle="modal" data-target="#deleteModal"
                class="btn btn-sm btn-danger w-100 my-2">Delete</button>
            <a href="#" class="btn btn-sm btn-success w-100 my-2">Archive</a>
        </div>
    </div>
    {% endif %}

    {% if department %}
    {% include "courses-app/modal/deleteModal.html" with url_name="delete_department" id=department.id %}
    {% endif %}

    {% endblock %}
    <!-- Specific JS goes HERE -->
    {% block javascripts %}
    {% endblock javascripts %}

back-end/LMS/apps/templates/courses-app/forms/form-lesson.html
{% extends 'includes/form.html' %}

{% block title %} Department Form {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}

{% block header_page %}
<!-- Table headers will go here -->
<h6 class="h2 text-white d-inline-block mb-0">Lesson</h6>
<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="/lessons">Lessons</a></li>
        {% if form_type == 'detail-form' %}
        <li class="breadcrumb-item active" aria-current="page">{{ lesson.name }}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Lesson</li>
        {% endif %}
    </ol>
</nav>
{% endblock %}


{% block header_form %}
<!-- this is header form -->
{% if form_type != 'detail-form' %}
<h1 class="mb-1">Create Lesson</h1>
<button id="courseButton" class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" style="display: none;">Save</button>
{% endif %}
{% endblock %}

{% block body_form %}
<!-- this is form content -->
    {% if form_type == 'detail-form' %}
    <form id="courseForm" action="{%url 'edit_lesson' lesson.id%}" method="post">
    {% else %}
    <form id="courseForm" action="{%url 'create_lesson' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
    </form>
    {% endblock %}

    {% block action_form %}
    <!-- this is form content if it eddit -->
    {% if form_type == 'detail-form' %}
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="mb-1">{{ lesson.name }}</h3>
            <a id="courseButton" href="#" class="btn btn-sm btn-info w-100 my-2" style=" display: none;">Save</a>
            <a href="#" class="btn btn-sm btn-info w-100 my-2">Duplicate</a>
            <button id="deleteCourse" data-toggle="modal" data-target="#deleteModal"
                class="btn btn-sm btn-danger w-100 my-2">Delete</button>
            <a href="#" class="btn btn-sm btn-success w-100 my-2">Archive</a>
        </div>
    </div>
    {% endif %}

    {% if lesson %}
    {% include "courses-app/modal/deleteModal.html" with url_name="delete_lesson" id=lesson.id %}
    {% endif %}

    {% endblock %}
    <!-- Specific JS goes HERE -->
    {% block javascripts %}
    {% endblock javascripts %}

back-end/LMS/apps/templates/courses-app/forms/form-video.html
{% extends 'includes/form.html' %}

{% block title %} Department Form {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}

{% block header_page %}
<!-- Table headers will go here -->
<h6 class="h2 text-white d-inline-block mb-0">Category</h6>
<nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="/categorys">Departments</a></li>
        {% if form_type == 'detail-form' %}
        <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Course</li>
        {% endif %}
    </ol>
</nav>
{% endblock %}


{% block header_form %}
<!-- this is header form -->
{% if form_type != 'detail-form' %}
<h1 class="mb-1">Create Course</h1>
<button id="courseButton" class="btn btn-sm btn-primary py-2 px-4 mx-3 mb-2" style="display: none;">Save</button>
{% endif %}
{% endblock %}

{% block body_form %}
<!-- this is form content -->
    {% if form_type == 'detail-form' %}
    <form id="courseForm" action="{%url 'edit_category' category.id%}" method="post">
    {% else %}
    <form id="courseForm" action="{%url 'create_category' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
    </form>
    {% endblock %}

    {% block action_form %}
    <!-- this is form content if it eddit -->
    {% if form_type == 'detail-form' %}
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="mb-1">{{ category.name }}</h3>
            <a id="courseButton" href="#" class="btn btn-sm btn-info w-100 my-2" style=" display: none;">Save</a>
            <a href="#" class="btn btn-sm btn-info w-100 my-2">Duplicate</a>
            <button id="deleteCourse" data-toggle="modal" data-target="#deleteModal"
                class="btn btn-sm btn-danger w-100 my-2">Delete</button>
            <a href="#" class="btn btn-sm btn-success w-100 my-2">Archive</a>
        </div>
    </div>
    {% endif %}

    {% if category %}
    {% include "courses-app/modal/deleteModal.html" with url_name="delete_category" id=category.id %}
    {% endif %}

    {% endblock %}
    <!-- Specific JS goes HERE -->
    {% block javascripts %}
    {% endblock javascripts %}